### ISSUE TITLE
[docs]: Update `README.md`

### ISSUE THREAD

**Issue by michaelgrigoryan25** [polygon-isecure/core#28]
We will need to update the documentation. We will need to document at least the steps that are required to create a local Polygon instance(e.g. Docker, PostgreSQL & Redis setup).

**Comment by mikayelgr** [comment]
Updated the documentation for development purposes. 

Related commits: b82489d7e1091d6e7d55dcd4d4f907c32d394d34, 05e432500affc2ac15228aa77d25971a3b707780, c1cb1e0ccaf388e8d2418673d3d16ce711ae7a4a.
